name: Generic PHP Action
description: Use the Composer CLI in your Github Actions.

inputs:
  php_version:
    description: What version of PHP to use
    default: latest
    required: false

  php_extensions:
    description: Space separated list of extensions to configure with the PHP build
    required: false

  command:
    description: Composer command to run
    required: true
    default: php -i

outputs:
  full_command:
    description: "The full command passed to docker to run"
    value: ${{ steps.composer_run.putputs.full_command }}

runs:
  using: "composite"
  steps:
    - env:
        ACTION_PHP_VERSION: ${{ inputs.php_version }}
        ACTION_PHP_EXTENSIONS: ${{ inputs.php_extensions }}
        ACTION_TOKEN: ${{ github.token }}
        ACTION_COMMAND: ${{ inputs.command }}
        ACTION_ARGS: ${{ inputs.args }}
      id: composer_run
      run: bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/330b13bbb1eadd05bbb627477c1549cd7e62e406/php-build.bash) generic \
        && ${{ github.action_path }}/generic-action.bash || { echo "::group::Debug output" ; cat ${{ github.workspace }}/output.log ; echo "::endgroup::" ; exit 1; }
      shell: bash

branding:
  icon: 'package'
  color: 'purple'
